apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: microservices-ns
type: Opaque
data:
  # Base64 encoded value of "unaclavesupersecreta123"
  JWT_KEY: dW5hY2xhdmVzdXBlcnNlY3JldGExMjM=
