# k8s/02-app-secret.yaml
# Gestiona los datos sensibles, como claves de API o credenciales.
# El valor de JWT_KEY est√° codificado en Base64.
# Para generar un nuevo valor: echo -n 'tu-clave-secreta' | base64
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: microservices-ns
type: Opaque
data:
  # Valor de 'unaclavesupersecreta123' codificado en Base64
  JWT_KEY: dW5hY2xhdmVzdXBlcnNlY3JldGExMjM=
